# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MusicalPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(866, 683)
        icon = QtGui.QIcon.fromTheme("dark_blue.xml")
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageLabel = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setText("")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prev = QtWidgets.QPushButton(self.tab_3)
        self.prev.setText("")
        self.prev.setObjectName("prev")
        self.horizontalLayout_2.addWidget(self.prev)
        self.play = QtWidgets.QPushButton(self.tab_3)
        self.play.setStyleSheet("*:before {\n"
"  pointer-events: none;\n"
"  position: absolute;\n"
"  z-index: -1;\n"
"  content: \'\';\n"
"  top: 100%;\n"
"  left: 5%;\n"
"  height: 10px;\n"
"  width: 90%;\n"
"  opacity: 0;\n"
"  background: -webkit-radial-gradient(center, ellipse, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0) 80%);\n"
"  background: radial-gradient(ellipse at center, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0) 80%);\n"
"  -webkit-transition-duration: 0.3s;\n"
"  transition-duration: 0.3s;\n"
"  -webkit-transition-property: -webkit-transform, opacity;\n"
"  transition-property: transform, opacity;\n"
"}\n"
"\n"
"*:hover {\n"
"  -webkit-transform: translateY(-5px);\n"
"  -ms-transform: translateY(-5px);\n"
"  transform: translateY(-5px);\n"
"}\n"
"*:hover:before {\n"
"  opacity: 1;\n"
"  -webkit-transform: translateY(5px);\n"
"  -ms-transform: translateY(5px);\n"
"  transform: translateY(5px);\n"
"}")
        self.play.setText("")
        self.play.setObjectName("play")
        self.horizontalLayout_2.addWidget(self.play)
        self.next = QtWidgets.QPushButton(self.tab_3)
        self.next.setText("")
        self.next.setObjectName("next")
        self.horizontalLayout_2.addWidget(self.next)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.volumeShow = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeShow.sizePolicy().hasHeightForWidth())
        self.volumeShow.setSizePolicy(sizePolicy)
        self.volumeShow.setText("")
        self.volumeShow.setObjectName("volumeShow")
        self.horizontalLayout_3.addWidget(self.volumeShow)
        self.volume = QtWidgets.QSlider(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume.sizePolicy().hasHeightForWidth())
        self.volume.setSizePolicy(sizePolicy)
        self.volume.setMaximum(100)
        self.volume.setProperty("value", 50)
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setObjectName("volume")
        self.horizontalLayout_3.addWidget(self.volume)
        self.currentTime = QtWidgets.QLabel(self.tab_3)
        self.currentTime.setText("")
        self.currentTime.setObjectName("currentTime")
        self.horizontalLayout_3.addWidget(self.currentTime)
        self.progress = QtWidgets.QSlider(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress.sizePolicy().hasHeightForWidth())
        self.progress.setSizePolicy(sizePolicy)
        self.progress.setOrientation(QtCore.Qt.Horizontal)
        self.progress.setTickInterval(0)
        self.progress.setObjectName("progress")
        self.horizontalLayout_3.addWidget(self.progress)
        self.allTime = QtWidgets.QLabel(self.tab_3)
        self.allTime.setText("")
        self.allTime.setObjectName("allTime")
        self.horizontalLayout_3.addWidget(self.allTime)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.listSongs = QtWidgets.QListWidget(self.tab_3)
        self.listSongs.setObjectName("listSongs")
        self.horizontalLayout.addWidget(self.listSongs)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.artistButton = QtWidgets.QPushButton(self.tab_4)
        self.artistButton.setObjectName("artistButton")
        self.verticalLayout_6.addWidget(self.artistButton)
        self.listArtists = QtWidgets.QListWidget(self.tab_4)
        self.listArtists.setObjectName("listArtists")
        self.verticalLayout_6.addWidget(self.listArtists)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.listAlbums = QtWidgets.QListWidget(self.tab)
        self.listAlbums.setObjectName("listAlbums")
        self.verticalLayout_7.addWidget(self.listAlbums)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Проигрыватель"))
        self.artistButton.setText(_translate("MainWindow", "Добавить исполнителя"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Исполнители"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Альбомы"))
        self.menu.setTitle(_translate("MainWindow", "Песня"))
        self.action.setText(_translate("MainWindow", "Открыть"))
        self.action_2.setText(_translate("MainWindow", "Открыть"))
